{"name": "Проверка неуспешного обновления пользователя", "status": "passed", "start": 1715753453940, "stop": 1715753454426, "uuid": "4fc62d24-6d5f-49ce-9b9b-90f724f02667", "historyId": "14c09b2df95b7e58a7d86d54c8f944ec", "testCaseId": "14c09b2df95b7e58a7d86d54c8f944ec", "fullName": "tests.test_authorization_user.TestAuthorizationUser#test_error_patch_user", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_authorization_user"}, {"name": "subSuite", "value": "TestAuthorizationUser"}, {"name": "host", "value": "maksimka"}, {"name": "thread", "value": "34724-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_authorization_user"}]}