{"name": "Проверка неуспешного логинизирования пользователя", "status": "passed", "start": 1715753462243, "stop": 1715753462567, "uuid": "38a80b6c-67bb-4258-9c54-5079e99a2fc2", "historyId": "264eb6cb97a747a9ed348ee58219393c", "testCaseId": "264eb6cb97a747a9ed348ee58219393c", "fullName": "tests.test_login_user.TestLoginUser#test_error_login_user", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_user"}, {"name": "subSuite", "value": "TestLoginUser"}, {"name": "host", "value": "maksimka"}, {"name": "thread", "value": "34724-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_user"}]}