{"name": "Проверка неуспешного логинизирования пользователя", "status": "passed", "start": 1715753421030, "stop": 1715753421413, "uuid": "600144ee-d307-4e0c-b714-5edfd251fb9b", "historyId": "264eb6cb97a747a9ed348ee58219393c", "testCaseId": "264eb6cb97a747a9ed348ee58219393c", "fullName": "tests.test_login_user.TestLoginUser#test_error_login_user", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_user"}, {"name": "subSuite", "value": "TestLoginUser"}, {"name": "host", "value": "maksimka"}, {"name": "thread", "value": "41204-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_user"}]}