{"name": "Проверка неуспешного обновления пользователя", "status": "passed", "start": 1715753414799, "stop": 1715753415094, "uuid": "5484a9c3-1f52-41c7-924c-3401afa31dfc", "historyId": "14c09b2df95b7e58a7d86d54c8f944ec", "testCaseId": "14c09b2df95b7e58a7d86d54c8f944ec", "fullName": "tests.test_authorization_user.TestAuthorizationUser#test_error_patch_user", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_authorization_user"}, {"name": "subSuite", "value": "TestAuthorizationUser"}, {"name": "host", "value": "maksimka"}, {"name": "thread", "value": "41204-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_authorization_user"}]}